name: cayread
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  archive: ^3.3.7
  collection: ^1.17.2
  colorful_safe_area: ^1.0.0
  file_picker: ^5.5.0
  get_it: ^7.6.0
  image: ^4.1.3
  injectable: ^2.2.0
  intl: ^0.18.1
  mime: ^1.0.4
  path: ^1.8.3
  path_provider: ^2.1.1
  share_plus: ^8.0.0
  sqlite_async: ^0.5.2
  synchronized: ^3.1.0
  uuid: ^3.0.7
  xml: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  injectable_generator: ^2.1.6
  build_runner: ^2.4.6
  dependency_validator: ^3.2.2


flutter:
  uses-material-design: true

  assets:
    - assets/index_script.js
    - assets/inject_script.js
    - assets/inject_style.css
